added cookiecutter, pre-commit, terraform-docs, tflint, tfsec
whalebrew/whalebrew-packages pull request #86
Opened 2020-10-10 19:11 UTC by aidanmelen

added the following whalebrew packages:

- cookiecutter
- pre-commit
- terraform-docs
- tflint
- tfsec

2020-10-14 10:58 UTC, tjamet requested changes
Thanks for the awesome contribution!
Can we manage to reduce the number of supported versions?

2020-10-15 01:28 UTC, aidanmelen commented on cookiecutter/tags.yaml
> +versions:
I can slim down the list.

2020-10-15 01:31 UTC, aidanmelen commented on tflint/Dockerfile
> +FROM wata727/tflint:${VERSION}
> Is this the official tflint image?

Yes, [source for github repo](https://github.com/terraform-linters/tflint#docker)

2020-10-15 01:31 UTC, aidanmelen commented on tfsec/Dockerfile
> +FROM liamg/tfsec:${VERSION}
Yes, [source from github repo](https://github.com/tfsec/tfsec#use-with-docker)

2020-10-25 15:51 UTC, tjamet approved these changes

2020-10-25 15:51 UTC, merged